name: Pipeline de Calidad Retail App

# ¿Cuándo corre el workflow?
on:
  push:
    branches: [ "produccion" ]
  pull_request:
    branches: [ "produccion" ]

env:
   FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

# Conjunto de tareas
jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Runner aislado en la 
    env: 
      DATABASE_ENGINE: ${{ vars.DATABASE_ENGINE }}  
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD}} 
   

    # Acciones secuenciales
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v6

      - name: Ejecutar Comando SH
        run: |
          echo "Ejecutando comando SH simulado..."
          echo "Conectando a la base de datos con ${DATABASE_ENGINE}..."
          echo "Autenticación exitosa con contraseña oculta."
          echo "${DATABASE_PASWORD}"

      - name: Simular Análisis de Calidad
        run: |
          echo "Iniciando análisis de SonarQube simulado..."
          echo "Revisando HTML y JS..."
          echo "✅ Código limpio y sin code smells."

      - name: Simular Pruebas Unitarias
        run: |
          echo "Ejecutando tests de la carpeta tests/..."
          echo "✅ logic.test.js - PASSED"
          echo "✅ html.test.js - PASSED"

      - name: Probar Secret
        run: |
          echo "Probando acceso al secreto..."
          echo "El secreto es: ${{ secrets.API_KEY_RETAIL }}"
          echo "✅ Si ves *** arriba, el secreto está protegido."